version: '2'
volumes:
  mysql_data: null
services:
  apache:
    build: ./apache
    ports:
      - '8000:80'
    volumes:
      - './www:/var/www/html'
    links:
      - mysql
    ulimits:
      stack: -1
    environment:
      - CRON_INTERVAL_SEC=60
      - 'SMTP_MAILHUB=smtp.yandex.ru:465'
      - SMTP_USER=server@pdd-host.ru
      - SMTP_PASS=password
      - SMTP_REWRITE_DOMAIN=pdd-host.ru
      - SMTP_HOSTNAME=www.host.ru
      - XDEBUG_CONFIG = "remote_host=172.22.0.4 remote_enable=1"
      - PHP_IDE_CONFIG = "serverName=Docker"
  mysql:
    build: ./mysql
    volumes:
      - './mysql_data:/var/lib/mysql'
    environment:
      - MYSQL_USER=bitrix
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=bitrix
      - MYSQL_ROOT_PASSWORD=password2
  adminer:
    image: adminer
    ports:
      - '8080:8080'
